services:
  - type: cron
    name: btc-5min-scanner
    env: python
    buildCommand: ""
    startCommand: python scanner_5min.py
    schedule: "*/5 * * * *"   # Every 5 minutes UTC

  - type: cron
    name: btc-hourly-summary
    env: python
    buildCommand: ""
    startCommand: python summary_1hr.py
    schedule: "0 * * * *"     # Every hour UTC
